import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/Layout";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Input from "@/components/Input";
import StatisticsSection from "@/components/StatisticsSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Shortly - Shorten URLs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <Layout>
        <Navbar></Navbar>
        <section>
          <Hero />
        </section>
      </Layout>
      <section className="grayBg">
        <div className="inputContainer">
          <Input />
        </div>
      </section>
      <section className=" grayBg">
        <StatisticsSection />
      </section>
    </>
  );
}
